version: '2.0'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./db/custom:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  redis:
    image: redis
    restart: always

  app:  
    build: ./app
    restart: always
    ports:
      - 11164:80
    volumes:
      - ./nextcloud/nextcloud-files:/var/www/html
      - ./nextcloud/nextcloud-data:/var/www/html/data
      - ./nextcloud/nextcloud-config:/var/www/html/config
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    build: ./app
    restart: always
    volumes:
      - ./nextcloud/nextcloud-files:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
