version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
        - "db:/var/lib/mysql"
    environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_USER=nextcloud
        - MYSQL_PASSWORD=nextcloud
        - MYSQL_DATABASE=nextcloud

  app:
    image: nextcloud:13-apache
    volumes:
      - ./nextcloud:/var/www/html
    ports:
        - 11164:80
    environment:
        - MYSQL_HOST=db
        - MYSQL_USER=nextcloud
        - MYSQL_PASSWORD=nextcloud
        - MYSQL_DATABASE=nextcloud
    depends_on:
        - db

  cron:
    image: nextcloud:13-apache
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
        - db
